---
title: "KadamN_Project"
author: "Nisarga Kadam"
date: "2022-11-17"
output: html_document
---




```{r}
rm(list = ls())
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readxl)
labor_force <- read_excel("/Users/nisar/Desktop/Penn State 2022-2023/FALL/SODA496/LFPR.xlsx", skip = 5)
so_spending <- read.csv("/Users/nisar/Desktop/Penn State 2022-2023/FALL/SODA496/social-expenditure-as-percentage-of-gdp.csv")
```






```{r}


labor_force <- 
  labor_force %>% 
  select("Reference area", "Source", "Sex", "Age", "Time", "Total", "Single / Widowed / Divorced", "Married / Union / Cohabiting")

labor_force <- na.omit(labor_force)

labor_force <- 
  labor_force %>%
  rename(
    Total = "Total",
    single_widowed_divorced = `Single / Widowed / Divorced`,
    married_union_cohabiting = `Married / Union / Cohabiting`
  )

so_spending <- 
  so_spending %>%
  rename( family = "Social.expenditure.on.family....of.GDP...OECD.Stats..2019..",
          health = "Social.expenditure.on.health....of.GDP...OECD.Stats..2019..",
          housing = "Social.expenditure.on.housing....of.GDP...OECD.Stats..2019..",
          disability = "Incapacity.related.social.expenditures....of.GDP...OECD.Stats..2019..",
          oldAge = "Old.age.related.social.expenditures....of.GDP...OECD.Stats..2019..",
          otherPolicy = "Social.expenditure.on.other.social.policy.areas....of.GDP...OECD.Stats..2019..",
          survivors = "Social.expenditure.on.survivors....of.GDP...OECD.Stats..2019..",
          unemployment = "Social.expenditure.on.unemployment....of.GDP...OECD.Stats..2019..",
          labormktPolicy = "Social.expenditure.on.active.labor.market.policies....of.GDP...OECD.Stats..2019.."
          
          )
so_spending <- na.omit(so_spending)
```

```{r}

comb <- inner_join(labor_force,so_spending, by = c("Reference area" = "Entity", "Time" = "Year"))

comb <- filter(comb, Sex == "Female")

```




```{r}
set.seed(12345)
train_ind <- sample(1:nrow(comb), floor(.8*nrow(comb)))
set.seed(NULL)

Train <- comb[train_ind,]
Test <- comb[-train_ind,]


```

```{r}



model<- lm(Total ~ single_widowed_divorced + married_union_cohabiting+family  , data= Train)
summary(model)

```



```{r}

yhat <- predict(model, newdata=Test)


```


```{r}
MSE1 <- mean((Test$Total-yhat)^2)
MSE1

RMSE1 <- sqrt(MSE1)
RMSE1




```










